from langgraph.graph import StateGraph, START, END
from .state import AgentState
from .nodes import analyze_node, decision_agent_node, tool_node

def should_continue(state: AgentState):
    """
    The Router! This checks the very last message generated by the `decision_agent_node`.
    If the LLM decided to use a tool, it routes to "tool_node".
    If the LLM didn't use a tool (meaning it finished), it routes to END.
    """
    messages = state["messages"]
    last_message = messages[-1]

    # Check if the LLM outputted any tool_calls
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        print(f"  -> Agent decided to use {len(last_message.tool_calls)} tools!")
        return "tools" # Go to the tool_node
    
    print("  -> Agent is finished routing data to the database.")
    return "END"

def build_graph():
    workflow = StateGraph(AgentState)
    
    # 1. Add all nodes
    workflow.add_node("analyze_node", analyze_node)
    workflow.add_node("decision_agent", decision_agent_node) # This is your agent!
    workflow.add_node("tool_node", tool_node)           
    
    # 2. Linear sequence at the start
    workflow.add_edge(START, "analyze_node")
    workflow.add_edge("analyze_node", "decision_agent")
    
    # 3. The Conditional Edge (The Loop logic)
    workflow.add_conditional_edges(
        "decision_agent",
        should_continue,
        {
            "tools": "tool_node", 
            "END": END            
        }
    )
    
    # 4. End after one tool execution pass
    workflow.add_edge("tool_node", END)
    
    return workflow.compile()