-- Restore core backend tables (non-GraphRAG only).
-- Intentionally excludes GraphRAG/syllabus tables such as:
-- concepts, concept_dependencies, student_weak_concepts, remediation_exercises,
-- syllabi, syllabus_entities, syllabus_relationships, knowledge_documents, knowledge_embeddings.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  display_name text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.students (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  student_id text NOT NULL,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT students_teacher_id_fkey
    FOREIGN KEY (teacher_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT students_teacher_uuid_unique UNIQUE (teacher_id, id),
  CONSTRAINT students_teacher_student_id_unique UNIQUE (teacher_id, student_id)
);

CREATE TABLE IF NOT EXISTS public.assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id uuid NOT NULL,
  title text NOT NULL,
  subject text,
  total_marks integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT assignments_teacher_id_fkey
    FOREIGN KEY (teacher_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.questions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id uuid NOT NULL,
  assignment_id integer NOT NULL,
  question_label text NOT NULL,
  question_description text NOT NULL,
  marks integer,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT questions_teacher_fkey
    FOREIGN KEY (teacher_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT questions_assignment_fkey
    FOREIGN KEY (assignment_id) REFERENCES public.assignments(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.rubrics (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id uuid NOT NULL,
  assignment_id integer NOT NULL,
  question_label text NOT NULL,
  rubric_description jsonb NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT rubrics_teacher_fkey
    FOREIGN KEY (teacher_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT rubrics_assignment_fkey
    FOREIGN KEY (assignment_id) REFERENCES public.assignments(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.teacher_solutions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id uuid NOT NULL,
  assignment_id integer NOT NULL,
  question_label text NOT NULL,
  solution_text text NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT teacher_solutions_teacher_fkey
    FOREIGN KEY (teacher_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT teacher_solutions_assignment_fkey
    FOREIGN KEY (assignment_id) REFERENCES public.assignments(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.student_answers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id uuid NOT NULL,
  student_id uuid NOT NULL,
  assignment_id integer NOT NULL,
  question_label text NOT NULL,
  answer text NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT student_answers_assignment_fkey
    FOREIGN KEY (assignment_id) REFERENCES public.assignments(id) ON DELETE CASCADE,
  CONSTRAINT student_answers_student_fkey
    FOREIGN KEY (teacher_id, student_id) REFERENCES public.students(teacher_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.student_question_scores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id uuid NOT NULL,
  student_id uuid NOT NULL,
  assignment_id integer NOT NULL,
  question_label text NOT NULL,
  question_text text,
  student_solution text,
  marks numeric NOT NULL DEFAULT 0,
  confidence_score numeric NOT NULL DEFAULT 0,
  ai_comment text,
  teacher_comment text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT student_question_scores_assignment_fkey
    FOREIGN KEY (assignment_id) REFERENCES public.assignments(id) ON DELETE CASCADE,
  CONSTRAINT student_question_scores_student_fkey
    FOREIGN KEY (teacher_id, student_id) REFERENCES public.students(teacher_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.ai_evaluations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_answer_id integer NOT NULL,
  final_score numeric,
  final_feedback text,
  detailed_marks jsonb NOT NULL,
  confidence_score numeric,
  evaluation_metadata jsonb,
  evaluated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ai_evaluations_answer_fkey
    FOREIGN KEY (student_answer_id) REFERENCES public.student_answers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.teacher_reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evaluation_id integer NOT NULL,
  teacher_score numeric,
  teacher_feedback text,
  approved boolean DEFAULT false,
  reviewed_at timestamptz DEFAULT now(),
  CONSTRAINT teacher_reviews_evaluation_fkey
    FOREIGN KEY (evaluation_id) REFERENCES public.ai_evaluations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.grading_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  assignment_id integer NOT NULL,
  student_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'queued',
  created_at timestamptz DEFAULT now(),
  completed_at timestamptz,
  CONSTRAINT grading_jobs_assignment_fkey
    FOREIGN KEY (assignment_id) REFERENCES public.assignments(id) ON DELETE CASCADE,
  CONSTRAINT grading_jobs_teacher_fkey
    FOREIGN KEY (teacher_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT grading_jobs_student_fkey
    FOREIGN KEY (teacher_id, student_id) REFERENCES public.students(teacher_id, id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_assignments_teacher_id
  ON public.assignments(teacher_id);

CREATE INDEX IF NOT EXISTS idx_students_teacher_id
  ON public.students(teacher_id);

CREATE INDEX IF NOT EXISTS idx_questions_assignment
  ON public.questions(assignment_id);

CREATE INDEX IF NOT EXISTS idx_questions_teacher_assignment
  ON public.questions(teacher_id, assignment_id);

CREATE INDEX IF NOT EXISTS idx_rubrics_assignment
  ON public.rubrics(assignment_id);

CREATE INDEX IF NOT EXISTS idx_teacher_solutions_assignment
  ON public.teacher_solutions(assignment_id);

CREATE INDEX IF NOT EXISTS idx_student_answers_assignment
  ON public.student_answers(assignment_id);

CREATE INDEX IF NOT EXISTS idx_student_answers_student
  ON public.student_answers(student_id);

CREATE INDEX IF NOT EXISTS idx_student_question_scores_assignment
  ON public.student_question_scores(assignment_id);

CREATE INDEX IF NOT EXISTS idx_student_question_scores_student
  ON public.student_question_scores(student_id);

CREATE INDEX IF NOT EXISTS idx_student_question_scores_teacher_assignment_student
  ON public.student_question_scores(teacher_id, assignment_id, student_id);

CREATE INDEX IF NOT EXISTS idx_ai_evaluations_answer
  ON public.ai_evaluations(student_answer_id);

CREATE UNIQUE INDEX IF NOT EXISTS rubrics_teacher_assignment_question_label_unique
  ON public.rubrics (
    teacher_id,
    assignment_id,
    regexp_replace(lower(question_label), '\s+', '', 'g')
  );

CREATE OR REPLACE FUNCTION public.set_updated_at_student_question_scores()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_student_question_scores_updated_at ON public.student_question_scores;
CREATE TRIGGER trg_student_question_scores_updated_at
BEFORE UPDATE ON public.student_question_scores
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_student_question_scores();
